//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public int TitleID { get; set; }
    
        public virtual Title Title { get; set; }

        static Employe emp;

        public static Employe createEmploye(int ID, string Surname, string Name, 
                                            string Patronymic, int TitleID)
        {
            emp = new Employe();
            emp.ID = ID;
            emp.Surname = Surname;
            emp.Name = Name;
            emp.Patronymic = Patronymic;
            emp.TitleID = TitleID;
            emp.Telephone = "Не задано";
            emp.Email = "Не задано";

            return emp;
        }
    }
}
